name: how-much-logs-can-a-keylogger-log-if-a-keylogger-could-log-logs

services:
  postgres:
    image: postgres
    container_name: how-much-logs-can-a-keylogger-log-if-a-keylogger-could-log-logs-postgres
    environment:
      POSTGRES_DB: how-much-logs-can-a-keylogger-log-if-a-keylogger-could-log-logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - how-much-logs-can-a-keylogger-log-if-a-keylogger-could-log-logs_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  how-much-logs-can-a-keylogger-log-if-a-keylogger-could-log-logs_postgres_data:
